name: flutter_mvc
description: "MVC template Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^5.4.0
  flutter_screenutil: ^5.9.0
  shared_preferences: ^2.2.2
  page_transition: ^2.1.0
  provider: ^6.1.1
  internet_connection_checker: ^1.0.0+1
  dartz: ^0.10.1
  double_back_to_close: ^2.0.0
  fluttertoast: ^8.2.4
  intl: ^0.18.1
  jwt_decoder: ^2.0.1
  google_nav_bar: ^5.0.6



  #  calendar_date_picker2: ^0.5.3
  #  mobile_scanner: ^3.5.5
  #  image_collage: ^0.0.4
  #  flutter_rating_bar: ^4.0.1
  #  image_picker: ^1.0.7
  #  animated_custom_dropdown: ^2.0.0
  #  file_picker: ^8.0.0+1
  #  flutter_file_downloader: ^1.2.1
  #  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
#  flutter_launcher_icons: ^0.13.1

#flutter_launcher_icons:
#  android: "launcher_icon"
#  ios: true
#  image_path: "assets/images/logo_icon.png"

flutter:
  generate: true

  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/


#  fonts:
#    - family: MyDecorations.myFont
#      fonts:
#        - asset: assets/fonts/Saira-Regular.ttf
#          weight: 400
#        - asset: assets/fonts/Saira-Medium.ttf
#          weight: 500
#        - asset: assets/fonts/Saira-SemiBold.ttf
#          weight: 600
#    - family: MyIcons
#      fonts:
#        - asset: assets/fonts/MyIcons.ttf
